image: node:latest

cache:
    paths:
    - node_modules/

before_script:
    - yarn

build:
    stage: build
    script:
        - yarn build

report:
    stage: test
    script:
        - yarn report

pages:
    stage: deploy
    only:
        - master
    script:
        - yarn report
        - yarn deploy
    artifacts:
        paths:
            - public
